version: '3'
services:

  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hashtagcms/create-app
    container_name: ${APP_CONTAINER_NAME:-hashtagcms-app}
    restart: unless-stopped
    tty: true
    depends_on:
      db:
        condition: service_healthy
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - hashtagcms-network

  # Nginx Service
  web:
    image: nginx:alpine
    container_name: ${WEB_CONTAINER_NAME:-hashtagcms-web}
    restart: unless-stopped
    tty: true
    ports:
      - "127.0.0.1:${WEB_PORT:-8081}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - hashtagcms-network

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: ${DB_CONTAINER_NAME:-hashtagcms-db}
    restart: unless-stopped
    tty: true
    ports:
      - "127.0.0.1:${DB_PORT_EXTERNAL:-3306}:3306"
    environment:
      MYSQL_DATABASE: hashtagcms
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: hashtagcms
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      # CAUTION: Data is persisted outside the container at ./docker/mysql
      # Do not remove this mapping unless you want to lose your data on container rebuild.
      - ./docker/mysql:/var/lib/mysql
    networks:
      - hashtagcms-network

networks:
  hashtagcms-network:
    driver: bridge
